// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Clip {
    "id": string;
    "type": string;

    /**
     * truncated preview for text; full text via GetClipContent
     */
    "content"?: string | null;

    /**
     * base64 - thumbnail for list, full-res on demand
     */
    "image"?: string | null;
    "isPinned": boolean;
    "createdAt": string;
    "label": string;
    "isHidden": boolean;

    /**
     * "local" (default) or "network"
     */
    "source"?: string;

    /** Creates a new Clip instance. */
    constructor($$source: Partial<Clip> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("isPinned" in $$source)) {
            this["isPinned"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("isHidden" in $$source)) {
            this["isHidden"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Clip instance from a string or object.
     */
    static createFrom($$source: any = {}): Clip {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Clip($$parsedSource as Partial<Clip>);
    }
}
