// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./backend/store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddClip(content: string, pinned: boolean): $CancellablePromise<void> {
    return $Call.ByID(3170530730, content, pinned);
}

export function AddIgnoreEntry(name: string): $CancellablePromise<void> {
    return $Call.ByID(1243036326, name);
}

/**
 * ConfirmDelete shows a native Yes/No dialog and returns true if the user
 * confirmed the deletion. The message is shown as the dialog body.
 */
export function ConfirmDelete(message: string): $CancellablePromise<boolean> {
    return $Call.ByID(1149614580, message);
}

export function Delete(clipID: number): $CancellablePromise<void> {
    return $Call.ByID(1990065762, clipID);
}

export function DeleteAllClips(): $CancellablePromise<void> {
    return $Call.ByID(2186694156);
}

export function DeletePinnedClips(): $CancellablePromise<void> {
    return $Call.ByID(1324683243);
}

export function DeleteUnpinnedClips(): $CancellablePromise<void> {
    return $Call.ByID(1625961018);
}

export function DisableStartup(): $CancellablePromise<void> {
    return $Call.ByID(2374125532);
}

export function EnableStartup(): $CancellablePromise<void> {
    return $Call.ByID(561757899);
}

/**
 * FocusAndPaste focuses the previously active window and simulates Ctrl+V.
 * Call this after writing image data to the clipboard from the frontend via
 * the Web Clipboard API, which produces a format apps can reliably paste.
 */
export function FocusAndPaste(): $CancellablePromise<void> {
    return $Call.ByID(194495199);
}

export function GetAlwaysOnTop(): $CancellablePromise<boolean> {
    return $Call.ByID(2564677270);
}

export function GetAutoHideSensitive(): $CancellablePromise<boolean> {
    return $Call.ByID(43147748);
}

/**
 * GetClipContent returns the full, untruncated text of a clip. List/search
 * payloads only carry a truncated preview, so copy/edit/view fetch the full
 * text through this binding.
 */
export function GetClipContent(clipID: number): $CancellablePromise<string> {
    return $Call.ByID(2561889774, clipID);
}

export function GetClipImage(clipID: number): $CancellablePromise<string> {
    return $Call.ByID(2045734190, clipID);
}

/**
 * --------------------------------------------------------------------------------
 * Clip Management Functions
 * --------------------------------------------------------------------------------
 */
export function GetClips(): $CancellablePromise<store$0.Clip[]> {
    return $Call.ByID(1385906382).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetCursorSnap(): $CancellablePromise<boolean> {
    return $Call.ByID(3752887157);
}

export function GetDistinctLabels(): $CancellablePromise<string[]> {
    return $Call.ByID(1333104408).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetIgnoreList(): $CancellablePromise<string[]> {
    return $Call.ByID(1882610001).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetPlatform returns the current OS: "darwin", "linux", or "windows".
 */
export function GetPlatform(): $CancellablePromise<string> {
    return $Call.ByID(3709063056);
}

export function GetQuickPaste(): $CancellablePromise<boolean> {
    return $Call.ByID(1170946213);
}

/**
 * --------------------------------------------------------------------------------
 * Storage Limit Functions
 * --------------------------------------------------------------------------------
 */
export function GetStorageLimit(): $CancellablePromise<number> {
    return $Call.ByID(1034248375);
}

/**
 * GetSyncPeerCount returns the number of currently connected LAN peers.
 */
export function GetSyncPeerCount(): $CancellablePromise<number> {
    return $Call.ByID(516677299);
}

/**
 * GetSyncSettings returns the current sync configuration.
 */
export function GetSyncSettings(): $CancellablePromise<$models.SyncSettings> {
    return $Call.ByID(735283925).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * exposes app version to frontend
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(1049863377);
}

export function HideClip(clipID: number): $CancellablePromise<void> {
    return $Call.ByID(284457035, clipID);
}

export function IsMiniClip(): $CancellablePromise<boolean> {
    return $Call.ByID(51420468);
}

export function IsPaused(): $CancellablePromise<boolean> {
    return $Call.ByID(2583346675);
}

export function IsStartupEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(3872694095);
}

export function MakeMiniClip(value: boolean): $CancellablePromise<void> {
    return $Call.ByID(1582290926, value);
}

/**
 * PasteImageToWindow writes the image for the given clip ID to the system
 * clipboard as raw image data, then pastes it into the previously focused window.
 */
export function PasteImageToWindow(clipID: number): $CancellablePromise<void> {
    return $Call.ByID(3182570128, clipID);
}

export function PasteToWindow(content: string): $CancellablePromise<void> {
    return $Call.ByID(2308642809, content);
}

export function PauseCapture(): $CancellablePromise<void> {
    return $Call.ByID(2598102529);
}

export function RemoveIgnoreEntry(name: string): $CancellablePromise<void> {
    return $Call.ByID(3054561885, name);
}

export function RenameClip(clipID: number, label: string): $CancellablePromise<void> {
    return $Call.ByID(3217659325, clipID, label);
}

export function ResumeCapture(): $CancellablePromise<void> {
    return $Call.ByID(2781540432);
}

/**
 * SaveSyncSettings persists the sync configuration and starts or stops the
 * sync manager accordingly.
 */
export function SaveSyncSettings(enabled: boolean, passphrase: string): $CancellablePromise<void> {
    return $Call.ByID(3943863286, enabled, passphrase);
}

/**
 * SearchClips returns clips whose stored text matches the query. Search runs
 * on the backend (clips are no longer stored encrypted), returning the same
 * []Clip model as GetClips with truncated previews.
 */
export function SearchClips(query: string): $CancellablePromise<store$0.Clip[]> {
    return $Call.ByID(3919633220, query).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SetAlwaysOnTop(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3581063306, enabled);
}

export function SetAutoHideSensitive(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(588674888, enabled);
}

export function SetCursorSnap(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1978339065, enabled);
}

export function SetQuickPaste(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2986224601, enabled);
}

export function TogglePin(clipID: number): $CancellablePromise<void> {
    return $Call.ByID(1646551020, clipID);
}

export function UnhideClip(clipID: number): $CancellablePromise<void> {
    return $Call.ByID(4104326260, clipID);
}

export function UpdateClipContent(clipID: number, newContent: string): $CancellablePromise<void> {
    return $Call.ByID(1819865811, clipID, newContent);
}

export function UpdateStorageLimit(newLimit: number): $CancellablePromise<void> {
    return $Call.ByID(183619716, newLimit);
}

// Private type creation functions
const $$createType0 = store$0.Clip.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $models.SyncSettings.createFrom;
