// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SyncSettings holds the frontend-facing LAN sync configuration.
 */
export class SyncSettings {
    "enabled": boolean;
    "passphrase": string;
    "peerCount": number;

    /** Creates a new SyncSettings instance. */
    constructor($$source: Partial<SyncSettings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("passphrase" in $$source)) {
            this["passphrase"] = "";
        }
        if (!("peerCount" in $$source)) {
            this["peerCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncSettings($$parsedSource as Partial<SyncSettings>);
    }
}
