// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function AddClip(arg1:string,arg2:boolean):Promise<void>;

export function AddIgnoreEntry(arg1:string):Promise<void>;

export function Delete(arg1:number):Promise<void>;

export function DeleteAllClips():Promise<void>;

export function DeletePinnedClips():Promise<void>;

export function DeleteUnpinnedClips():Promise<void>;

export function DisableStartup():Promise<void>;

export function EnableStartup():Promise<void>;

export function FocusAndPaste():Promise<void>;

export function GetAlwaysOnTop():Promise<boolean>;

export function GetAutoHideSensitive():Promise<boolean>;

export function GetClipImage(arg1:number):Promise<string>;

export function GetClips():Promise<Array<store.Clip>>;

export function GetCursorSnap():Promise<boolean>;

export function GetDistinctLabels():Promise<Array<string>>;

export function GetIgnoreList():Promise<Array<string>>;

export function GetPlatform():Promise<string>;

export function GetQuickPaste():Promise<boolean>;

export function GetStorageLimit():Promise<number>;

export function GetVersion():Promise<string>;

export function HideClip(arg1:number):Promise<void>;

export function IsMiniClip():Promise<boolean>;

export function IsPaused():Promise<boolean>;

export function IsStartupEnabled():Promise<boolean>;

export function MakeMiniClip(arg1:boolean):Promise<void>;

export function PasteImageToWindow(arg1:number):Promise<void>;

export function PasteToWindow(arg1:string):Promise<void>;

export function PauseCapture():Promise<void>;

export function RemoveIgnoreEntry(arg1:string):Promise<void>;

export function RenameClip(arg1:number,arg2:string):Promise<void>;

export function ResumeCapture():Promise<void>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetAutoHideSensitive(arg1:boolean):Promise<void>;

export function SetCursorSnap(arg1:boolean):Promise<void>;

export function SetQuickPaste(arg1:boolean):Promise<void>;

export function TogglePin(arg1:number):Promise<void>;

export function UnhideClip(arg1:number):Promise<void>;

export function UpdateClipContent(arg1:number,arg2:string):Promise<void>;

export function UpdateStorageLimit(arg1:number):Promise<void>;
