// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClip(arg1, arg2) {
  return window['go']['main']['App']['AddClip'](arg1, arg2);
}

export function AddIgnoreEntry(arg1) {
  return window['go']['main']['App']['AddIgnoreEntry'](arg1);
}

export function Delete(arg1) {
  return window['go']['main']['App']['Delete'](arg1);
}

export function DeleteAllClips() {
  return window['go']['main']['App']['DeleteAllClips']();
}

export function DeletePinnedClips() {
  return window['go']['main']['App']['DeletePinnedClips']();
}

export function DeleteUnpinnedClips() {
  return window['go']['main']['App']['DeleteUnpinnedClips']();
}

export function DisableStartup() {
  return window['go']['main']['App']['DisableStartup']();
}

export function EnableStartup() {
  return window['go']['main']['App']['EnableStartup']();
}

export function FocusAndPaste() {
  return window['go']['main']['App']['FocusAndPaste']();
}

export function GetAlwaysOnTop() {
  return window['go']['main']['App']['GetAlwaysOnTop']();
}

export function GetAutoHideSensitive() {
  return window['go']['main']['App']['GetAutoHideSensitive']();
}

export function GetClipImage(arg1) {
  return window['go']['main']['App']['GetClipImage'](arg1);
}

export function GetClips() {
  return window['go']['main']['App']['GetClips']();
}

export function GetDistinctLabels() {
  return window['go']['main']['App']['GetDistinctLabels']();
}

export function GetIgnoreList() {
  return window['go']['main']['App']['GetIgnoreList']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetQuickPaste() {
  return window['go']['main']['App']['GetQuickPaste']();
}

export function GetStorageLimit() {
  return window['go']['main']['App']['GetStorageLimit']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HideClip(arg1) {
  return window['go']['main']['App']['HideClip'](arg1);
}

export function IsMiniClip() {
  return window['go']['main']['App']['IsMiniClip']();
}

export function IsPaused() {
  return window['go']['main']['App']['IsPaused']();
}

export function IsStartupEnabled() {
  return window['go']['main']['App']['IsStartupEnabled']();
}

export function MakeMiniClip(arg1) {
  return window['go']['main']['App']['MakeMiniClip'](arg1);
}

export function PasteImageToWindow(arg1) {
  return window['go']['main']['App']['PasteImageToWindow'](arg1);
}

export function PasteToWindow(arg1) {
  return window['go']['main']['App']['PasteToWindow'](arg1);
}

export function PauseCapture() {
  return window['go']['main']['App']['PauseCapture']();
}

export function RemoveIgnoreEntry(arg1) {
  return window['go']['main']['App']['RemoveIgnoreEntry'](arg1);
}

export function RenameClip(arg1, arg2) {
  return window['go']['main']['App']['RenameClip'](arg1, arg2);
}

export function ResumeCapture() {
  return window['go']['main']['App']['ResumeCapture']();
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetAutoHideSensitive(arg1) {
  return window['go']['main']['App']['SetAutoHideSensitive'](arg1);
}

export function SetQuickPaste(arg1) {
  return window['go']['main']['App']['SetQuickPaste'](arg1);
}

export function TogglePin(arg1) {
  return window['go']['main']['App']['TogglePin'](arg1);
}

export function UnhideClip(arg1) {
  return window['go']['main']['App']['UnhideClip'](arg1);
}

export function UpdateClipContent(arg1, arg2) {
  return window['go']['main']['App']['UpdateClipContent'](arg1, arg2);
}

export function UpdateStorageLimit(arg1) {
  return window['go']['main']['App']['UpdateStorageLimit'](arg1);
}
